### ISSUE TITLE
redis_example.ini should have empty telemetry file fields

### ISSUE THREAD

**Issue by the-other-james** [nasa/OnAIR#107]
TelemetryDataFilePath and TelemetryFile are ignored when using a data source, and thus should be left blank.

Related #101

**Comment by the-other-james** [comment]
Taking a closer look... the meta file doesn't make sense to me either. Is the subscription info hard-coded?

**Comment by asgibson** [comment]
The meta file will contain this information, but the .ini for this has not been updated to be used as an effective example as of yet. Redis had been added for use by a project and their .ini made use of this. The parsing of the meta file is done in the \_\_init__ function of any OnAirDataSource. Redis adapter's function, `parse_meta_data_file`, extracts subscription information from the meta file.
