### ISSUE TITLE
Planners plugin doesn't update?

### ISSUE THREAD

**Issue by the-other-james** [nasa/OnAIR#117]
I tried adding a custom plugin as a Planners plugin, and it doesn't appear to run (the plugin works fine as a Knowledge or Learners plugin).

It is possible that this has already been resolved, currently on a branch for #42

**Comment by asgibson** [comment]
Planners only `pass` as set right now:
https://github.com/nasa/OnAIR/blob/c2e1d4277b239a696d3d0290ccd90cd896917072/onair/src/ai_components/planners_interface.py#L16-L31
