### ISSUE TITLE
Add Docstrings adhering PEP

### ISSUE THREAD

**Issue by rajveer43** [nasa/OnAIR#46]

**Comment by asgibson** [comment]
Hello @rajveer43 and thank you for your interest in collaboration!

To submit a pull request for consideration please see the contributions guidelines:
https://github.com/nasa/OnAIR/tree/main#contributions

**Comment by asgibson** [comment]
Hi @rajveer43, unfortunately we are unable to review PRs for any contribution to the repository without the agreement.  
You can find full contribution details in the [Individual Contributor License Agreement (pdf)](https://github.com/nasa/OnAIR/blob/main/doc/Indv_CLA_OnAIR.pdf)

I reread the guide and it does state "If you would like to contribute code."  
It should read "If you would like to contribute to this repository."  
I will make sure that gets adjusted, #48

We look forward to reviewing your contribution!

**Comment by asgibson** [comment]
A good day to you, @rajveer43. To date, we have not received a collaboration agreement from you. Are you still interested in submitting one?

**Comment by rajveer43** [comment]
A very good day to you too,, I am not interested in any of the agreement.

**Comment by asgibson** [comment]
With the addition of Pylint, it will require these going forward. This issue is no longer necessary.
