### ISSUE TITLE
Reconsider naming convention for "vehicle_representation"

### ISSUE THREAD

**Issue by cfirth-nasa** [nasa/OnAIR#61]
Was brought up that the name "vehicle_representation" maybe does not fully represent the work that the class it creates actually does. "Vehicle_representation" suggests health/housekeeping (to me), whereas the actual class carries something more like a state space (containing information about the platform/system AND the environment). Is there a more accurate name for this subsystem?

**Comment by asgibson** [comment]
Here's a few ideas:
CognitiveEntityModel
AdaptiveEntity
AutonomousUnit
AutoBot (but then we'd need a rival class called Decepticon  :smirk:)

**Comment by cfirth-nasa** [comment]
Renamed to knowledge representation
