### ISSUE TITLE
Develop mechanism to set plugin execution order

### ISSUE THREAD

**Issue by cfirth-nasa** [nasa/OnAIR#64]
We might eventually require a way for plugins to be ordered to maintain data structures and keep internal data up-to-date; for example, if planning plugin B requires some output of planning plugin A, we should have a mechanism in place to ensure that planner A always runs before B.

We'd discussed using the order of the plugin dictionary (specified in the config file) to set the plugin execution order, but it might be beneficial (and a little fun) to try to find a way to do so automatically, based on required inputs/outputs to each plugin.

**Comment by asgibson** [comment]
The current implementation runs constructs in the order of their entry in the config file dict. I agree that providing a way to change that could be beneficial, but if ordering only gets set at config time then a user would only need to change the config file order prior to runtime. Could there be a need/desire to change the ordering of AI construct execution during runtime?

**Comment by the-other-james** [comment]
Ordering the plugins automatically is not possible since OnAIR has no knowledge of the outputs of each plugin (and thus can't reason about dependencies).

@cfirth-nasa is the current implementation (order is specified by the plugin order in the .ini config) sufficient? Please close if so.

**Comment by cfirth-nasa** [comment]
I think the current implementation gets the job done well enough!
