### ISSUE TITLE
Add COSMOS bin file parser

### ISSUE THREAD

**Issue by the-other-james** [nasa/OnAIR#7]
Allow OnAIR to parse the binary telemetry file created by the GSE, COSMOS, to be converted into usable telemetry points for diagnosis. Cosmos uses its own configuration file for the telemetry definitions, which includes any limits where they are used by COSMOS. The parser should use the bin and config COSMOS files to translate into OnAIR usable format.

**Comment by the-other-james** [comment]
From Alan: I think this could still be useful, especially for testing. However, I am concentrating on just running OnAIR in a container and having live telemetry flow.

**Comment by the-other-james** [comment]
While I see the utility; we do not have the resources to implement, test, and document this and we do not have a user (that I know of) who is interested in supporting parsing COSMOS bins and configs.

@asgibson , can we close this?

**Comment by asgibson** [comment]
Yes
